distribution_code_name: "ibus-rime"
distribution_name: Rime
distribution_version: 1.2
install_time: "Tue Jun  2 22:15:33 2015"
installation_id: "72292ea7-fb38-442e-a79f-fb799712327f"
rime_version: 1.2.9
update_time: "Thu Mar 10 21:52:17 2016"