custom_phrase:
  db_class: stabledb
  dictionary: ""
  enable_completion: false
  enable_sentence: false
  initial_quality: 1
  user_dict: custom_phrase
customization: 1181603097
engine:
  filters:
    - simplifier
    - uniquifier
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - "table_translator@custom_phrase"
    - script_translator
key_binder:
  import_preset: default
punctuator:
  import_preset: default
recognizer:
  import_preset: default
schema:
  author:
    - "佛振 <chen.sst@gmail.com>"
  description: |
    朙月拼音，臺灣正體字形輸出模式。
    
  name: "朙月拼音·臺灣正體"
  schema_id: luna_pinyin_tw
  version: 0.20.custom.1181603097
simplifier:
  opencc_config: t2tw.json
  option_name: zh_tw
speller:
  algebra:
    - "erase/^xx$/"
    - "derive/([ei])n$/$1ng/"
    - "derive/([ei])ng$/$1n/"
    - "abbrev/^([a-z]).+$/$1/"
    - "abbrev/^([zcs]h).+$/$1/"
    - "derive/^([nl])ve$/$1ue/"
    - "derive/^([jqxy])u/$1v/"
    - "derive/un$/uen/"
    - "derive/ui$/uei/"
    - "derive/iu$/iou/"
    - "derive/([aeiou])ng$/$1gn/"
    - "derive/([dtngkhrzcs])o(u|ng)$/$1o/"
    - "derive/ong$/on/"
    - "derive/ao$/oa/"
    - "derive/([iu])a(o|ng?)$/a$1$2/"
  alphabet: zyxwvutsrqponmlkjihgfedcba
  delimiter: " '"
switches:
  - name: ascii_mode
    reset: 0
    states: ["中文", "西文"]
  - name: full_shape
    states: ["半角", "全角"]
  - name: ascii_punct
    states: ["。，", "．，"]
  - name: zh_tw
    reset: 1
translator:
  dictionary: luna_pinyin
  preedit_format:
    - "xform/([nl])v/$1ü/"
    - "xform/([nl])ue/$1üe/"
    - "xform/([jqxy])v/$1u/"
  prism: luna_pinyin_tw